app/__init__.py
from flask import Flask, request
from app import config


app = Flask(__name__)

app.config.from_object(config.ProductionConfig)
app.config.from_object(config.DevelopmentConfig)

# load context processsor
from app.context_processors import *

# load template filters
from app import template_filters


# load web app views
from app.views.index import index_bp
from app.views.product import product_bp


app.register_blueprint(index_bp)
app.register_blueprint(product_bp)

app/views/index.py
from flask import Blueprint, render_template, redirect, flash, url_for, request


index_bp = Blueprint('index', __name__, url_prefix='/')


@index_bp.route('/')
def index():
	return render_template("index/index.html")


@index_bp.route('/signin-signup')
def signin_signup():
	return render_template("signin_signup/signin-signup.html")

app/views/product.py
from flask import Blueprint, render_template, redirect, flash, url_for, request


product_bp = Blueprint('product', __name__, url_prefix='/product')


class Product:
	name = "Beef Burger - Town Grill"
	preprice = "UGX 22,000"
	price = "UGX 16,000"


@product_bp.route('')
def get_products():
	# code to get /search products
	return {}


@product_bp.route('<int:product_id>')
def get_product(product_id):
	# code to get product
	product = Product()
	return render_template('product/product.html', product=product)

app/templates/base.html
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<title>Clickeat</title>

		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
		
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/font-awesome.min.css') }}">

		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/signin.css') }}">
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/app.css') }}">
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/skeleton-loader.css') }}">

		<script src="{{ url_for('static', filename='js/jquery-3.3.1.min.js') }}"></script>
	</head>

	<body>
		{% block body %}
		{% endblock %}
		<script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
		<script src="{{url_for('static', filename='js/number-input.js')}}"></script>
		<script src="{{url_for('static', filename='js/app.js')}}"></script>
		<script type="text/javascript">
			
		</script>
		
		{% include 'index/spinner-modal.html' %}
		
		{% block footer %}
		{% include 'index/prefooter.html' %}
		{% include 'index/footer.html' %}
		{% endblock %}
	</body>
</html>

app/templates/helpers.html
{% macro render_string_field(field) %}
	<div class='form-group'>
		<small>{{field.label.text}} {% if field|is_required %}<span class="text-danger">*</span>{% endif %}</small>
		{% if field.errors %}
			{{ field(class="form-control is-invalid", **kwargs)|safe }}
			<div class="invalid-feedback">
				{% for error in field.errors %}
					{{ error }}
				{% endfor %}
			</div>
		{% else %}
		{{ field(class="form-control", **kwargs)|safe }}
		{% endif %} 
	</div>
{% endmacro %}

{% macro render_telephone_field(field, code_field=None) %}
<div class="form-group">
	<small>{{field.label.text}} {% if field|is_required %}<span class="text-danger">*</span>{% endif %}</small>
	{% if field.errors %}
		{{ field(class="form-control is-invalid", **kwargs)|safe }}
		<div class="invalid-feedback">
			{% for error in field.errors %}
				{{ error }}
			{% endfor %}
		</div>
	{% else %}
	{% if code_field %}
	<div class="input-group">
		<div class="input-group-prepend">
          	{{ code_field }}
        </div>
        {% endif %}
		{{ field(class="form-control", **kwargs)|safe }}
		{% endif %} 
	</div>
</div>
{% endmacro %}

{% macro render_radio_field(field) %}
	<div class='form-group'>
		<small>{{field.label.text}} {% if field|is_required %}<span class="text-danger">*</span>{% endif %}</small>
		{% if field.errors %}
			<ul class="list-group list-group-horizontal">
			{% for subfield in field %}
				<li class="list-group-item my-auto">{{subfield}} {{subfield.label}}</li>
			{% endfor %}
			</ul>

			<div class="text-danger">
				{% for error in field.errors %}
					{{ error }}
				{% endfor %}
			</div>
		{% else %}
			<ul class="list-group list-group-horizontal">
			{% for subfield in field %}
				<li class="list-group-item my-auto">{{subfield}} {{subfield.label}}</li>
			{% endfor %}
			</ul>
		{% endif %} 
	</div>
{% endmacro %}

{% macro render_boolean_field(field) %}
	<div class='form-group'>
		{% if field.errors %}
			{{ field(class="is-invalid", **kwargs)|safe }}
			<div class="invalid-feedback">
				{% for error in field.errors %}
					{{ error }}
				{% endfor %}
			</div>
		{% else %}
			{{ field(**kwargs) }} 
			<label for="{{field.id}}">{{field.label.text}}</label>
		{% endif %} 
	</div>
{% endmacro %}


{% macro render_datetime_field(field, datetimepicker_id, datetime_format="DD MMMM YYYY", inline=False, min_date=None, max_date=None) %}
	<div class="form-group">
		<small>{{field.label.text}} {% if field|is_required %}<span class="text-danger">*</span>{% endif %}</small>
		{% if field.errors %}
			<div class="input-group date" id="{{datetimepicker_id}}" data-target-input="nearest"> 
				{{ field(type="text", class="form-control is-invalid datetimepicker-input", data_target="#{{datetimepicker_id}}", **kwargs)|safe }}
				<div class="input-group-append" data-target="#{{datetimepicker_id}}" data-toggle="datetimepicker"> 
					<div class="input-group-text {% if kwargs.get('hidden') %}d-none{% endif %}">
						<i class="fa fa-calendar"></i>
					</div> 
				</div>
				<div class="invalid-feedback">
					{% for error in field.errors %}
						{{ error }}
					{% endfor %}
				</div>
			</div>
		{% else %}
		<div class="input-group date" id="{{datetimepicker_id}}" data-target-input="nearest"> 
			{{ field(type="text", class="form-control datetimepicker-input", data_target='#'+datetimepicker_id, **kwargs)|safe }}
			<div class="input-group-append" data-target="#{{datetimepicker_id}}" data-toggle="datetimepicker"> 
				<div class="input-group-text {% if kwargs.get('hidden') %}d-none{% endif %}">
					<i class="fa fa-calendar"></i>
				</div> 
			</div> 
		</div> 
		{% endif %}
	</div> 
	{{ma}}
	<script type="text/javascript"> 
		$(function () {
			$('#{{datetimepicker_id}}').datetimepicker({
				"format":"{{datetime_format}}", 
				"useCurrent":false,
				{%if inline %}"inline":true,{%endif%}
				{%if min_date %}"minDate":'{{min_date}}',{%endif%}
				{%if max_date %}"maxDate":'{{max_date}}',{%endif%}
			}); 
		}); 
	</script> 
{% endmacro %}


{% macro render_UTC_field(field, datetimepicker_id) %}
	{{field(hidden="true")}}
	<script type="text/javascript"> 
		$(function () {
			$('#UTC_offset').val(moment().format('Z').replace(":", "")); 
		}); 
	</script> 
{% endmacro %}


{% macro render_select_field(field) %}
	<div class='form-group'>
		<small>{{field.label.text}} {% if field|is_required %}<span class="text-danger">*</span>{% endif %}</small>
		{% if field.errors %}
			{{ field(class="form-control is-invalid", **kwargs)|safe }}
			<div class="invalid-feedback">
				{% for error in field.errors %}
					{{ error }}
				{% endfor %}
			</div>
		{% else %}
		{{ field(**kwargs)|safe }}
	{% endif %} 
	</div>
{% endmacro %}


{% macro render_file_field(field, file_label_id) %}
	<small>{{field.label.text}} {% if field|is_required %}<span class="text-danger">*</span>{% endif %}</small>
	<div class="custom-file form-group">
		{% if field.errors %}
			{{ field(class="form-control is-invalid", **kwargs)|safe }}
			<div class="invalid-feedback">
				{% for error in field.errors %}
					{{ error }}
				{% endfor %}
			</div>
		{% else %}
		{{ field(class="custom-file-input", **kwargs)|safe }}
		<label id="{{file_label_id}}" class="custom-file-label shadow-sm text-nowrap" for="customFile"></label>
	{% endif %} 
	</div>
{% endmacro %}

{% macro render_pagination(pagination, endpoint, args={}) %}
	<nav aria-label="Page navigation example">
		<ul class="pagination justify-content-end">
			<!-- <li class="page-item"><a class="page-link" href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li> -->
			{% for page in pagination.iter_pages() %}
				{% if page %}
					{% if page != pagination.page %}
						<li class="page-item"><a class="page-link" href="{{url_for(endpoint, page=page)}}{{args|build_query_string}}">{{page}}</a></li>
					{% else %}
						<li class="page-item active" aria-current="page"><span class="page-link">{{page}}<span class="sr-only">(current)</span></span></li>
					{% endif %}
				{% else %}
					<span class="px-2 my-auto"> . . . </span>
				{% endif %}
			{% endfor %}
			<!-- <li class="page-item"><a class="page-link" href="#" aria-label="Next">
				<span aria-hidden="true">&raquo;</span>
				</a>
			</li> -->
		</ul>
	</nav>
{% endmacro %}

app/templates/index/banner.html
<section class="py-5 text-center container-fluid mt-" style="background-image: url({{url_for('static', filename='img/banner.png')}}); background-size: 100%; background-repeat: no-repeat;">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">Order Your Meal Now</h1>
      <p class="lead text-muted">Find Vast Categories of Scrumptious Delicacies From Various Outlets at Your Luxury</p>
      <!-- <p>
        <a href="#products" class="btn btn-primary my-2">Order Now</a>
      </p> -->
    </div>
  </div>
</section>

app/templates/index/footer.html
<footer class="footer mt-auto py-4">
  <div class="container text-center">
  	<p class="text-muted">Powered by AMOBIT Technologies <span>&copy;</span></p>
  </div>
</footer>

app/templates/index/header.html
<nav class="d-flex px-1 justify-content-between navbar navbar-dark navbar-expand-lg bg-dark">
	<div class="flex-fill">
		<a class="navbar-brand" href="/">
			<img class="rounded-circle" src="{{url_for('static', filename='img/logo-yellow.jpg')}}" alt="" width="50">
			Clickeat
		</a>
	</div>

	<button class="px-1 btn btn-dark"><span class="text-light fa fa-user fa-2x"></span></button>
	<button class="px-1 btn btn-dark"><span class="text-light fa fa-shopping-basket fa-2x"></span></button>

	<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<div class="px-2 mt-1" align="right">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				<li class="nav-item">
					<a class="nav-link" aria-current="page" href="{{url_for('index.signin_signup')}}">LOGIN | SIGNUP</a>
				</li>
			</ul>
		</div>
	</div>
</div>
</nav>

app/templates/index/index.html
{% extends 'base.html' %}

{% block body %}
	
	{% include 'index/header.html' %}
	{% include 'index/banner.html' %}
	{% include 'index/product-search.html' %}
	{% include 'index/products.html' %}

{% endblock %}

app/templates/index/prefooter.html
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
			<div class="col-md-4">
				<h2>Contact Us</h2>
				<div style="overflow-x: auto;">
					<table class="table table-bordered">
						<tbody>
							<tr>
								<td class="text-center"><span class="fa fa-phone fa-2x"></td>
								<td>0781902516</td>
							</tr>
							<tr>
								<td class="text-center"><span class="fa fa-envelope fa-2x"></td>
								<td>samuelitwaru@gmail.com</td>
							</tr>
							<tr>
								<td class="text-center"><span class="fa fa-facebook fa-2x"></td>
								<td>facebook.com/samuelitwaru</td>
							</tr>
							<tr>
								<td class="text-center"><span class="fa fa-twitter fa-2x"></td>
								<td>@samuelitwaru</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>

			<div class="col-md-4">
				<h2>Partners</h2>
				<table class="table">
					<tbody>
						<tr>
							<td class="text-center"><span class="fa fa-star-o"></td>
							<td>Bamboo Village</td>
						</tr>
						<tr>
							<td class="text-center"><span class="fa fa fa-star"></td>
							<td>Oasis</td>
						</tr>
						<tr>
							<td class="text-center"><span class="fa fa fa-star-o"></td>
							<td>Maisha</td>
						</tr>
						<tr>
							<td class="text-center"><span class="fa fa fa-star"></td>
							<td>Town Grill & BBQ</td>
						</tr>
						<tr>
							<td colspan="2"><a href="">More</a></td>
						</tr>
					</tbody>
				</table>
			</div>

			<div class="col-md-4">
				<h2>Do you have a bar or restaurant?</h2>
				<hr class="w-75">
				<div>
					<span class="fa fa-handshake-o fa-3x"></span>
					<div>
						<button class="btn btn-primary my-2">Partner with Us</button>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/templates/index/product-search.html
<section class="pt-3 pb-1 text-center container-fluid sticky-top rounded mb-4 shadow form-signin" style="background-image: linear-gradient(white, #f8f9fa);">
	<form id="searchProductForm" method="GET" action="{{url_for('product.get_products')}}">
		<div class="input-group input-group-lg">
			<!-- <span class="input-group-text" id="inputGroup-sizing-lg">Search</span> -->
			<input type="text" name="search" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" placeholder="Search Meal">
			<button type="submit" class="btn btn-warning" type="button"><span class="fa fa-search"></span></button>
		</div>
	</form>
</section>


<script type="text/javascript">
	$('#searchProductForm').submit((e)=>{
		e.preventDefault()
		showSpinnerModal()
		form = $(e.target)
		data = form.serialize()
		action = form.attr("action") 
		method = form.attr("method") 
		console.log(data)
		console.log(action)
		console.log(method)
		document.getElementById('products').scrollIntoView({behavior:"smooth"})
		// hideSpinnerModal()
	})
</script>

app/templates/index/products.html
<div class="album py-5 bg-light" id="products">
    <div class="container">
        <div class="d-flex justify-content-around flex-wrap">
            <div class="width-300 my-2">
                <div class="card shadow-sm">
                    <a href="{{url_for('product.get_product', product_id=1)}}">
                        <img data-loader="#imageLoader1" class="product-image bd-placeholder-img card-img-top hover-scale hover-opaque" width="100%" src="{{url_for('static', filename='img/banner1.jpeg')}}"  hidden="true"/>
                        <div id="imageLoader1" class="skeleton-loader-image"></div> 
                    </a>

                    <div class="card-body">
                        <p class="card-text">Beef Burger - Town Grill</p>
                        <strike class="text-warning">UGX 22,000</strike>
                        <p><strong>UGX 16,000</strong></p>
                        <div class="d-flex justify-content-between align-items-center">
                            <a href="{{url_for('product.get_product', product_id=1)}}" class="btn btn-primary hover-scale-2">Order</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="width-300 my-2">
                <div class="card shadow-sm">
                    <a href="{{url_for('product.get_product', product_id=1)}}">
                        <img data-loader="#imageLoader2" class="product-image bd-placeholder-img card-img-top hover-scale hover-opaque" width="100%" src="{{url_for('static', filename='img/banner2.jpg')}}" hidden="true"/>
                        <div id="imageLoader2" class="skeleton-loader-image"></div>
                    </a>

                    <div class="card-body">
                        <p class="card-text">Beef Burger - Town Grill</p>
                        <strike class="text-warning">UGX 22,000</strike>
                        <p><strong>UGX 16,000</strong></p>
                        <div class="d-flex justify-content-between align-items-center">
                            <a href="{{url_for('product.get_product', product_id=1)}}" class="btn btn-primary hover-scale-2">Order</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="width-300 my-2">
                <div class="card shadow-sm">
                    <a href="{{url_for('product.get_product', product_id=1)}}">
                        <img data-loader="#imageLoader3" class="product-image bd-placeholder-img card-img-top hover-scale hover-opaque" width="100%" src="{{url_for('static', filename='img/banner3.jpg')}}" hidden="true" />
                        <div id="imageLoader3" class="skeleton-loader-image"></div>
                    </a>

                    <div class="card-body">
                        <p class="card-text">Beef Burger - Town Grill</p>
                        <strike class="text-warning">UGX 22,000</strike>
                        <p><strong>UGX 16,000</strong></p>
                        <div class="d-flex justify-content-between align-items-center">
                            <a href="{{url_for('product.get_product', product_id=1)}}" class="btn btn-primary hover-scale-2">Order</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/templates/index/spinner-modal.html
<div class="modal" id="spinnerModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
        <div class="modal-body text-center">
            <div class="spinner-border text-warning" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
            <br>
            Please wait
        </div>
        </div>
    </div>
</div>

<script>
    var options = {
        backdrop: true,
        keyboard: true,
        focus: true
    }
    var myModal = new bootstrap.Modal(document.getElementById('spinnerModal'), options)
    function showSpinnerModal(){
    	myModal.show()
    }
    function hideSpinnerModal(){
    	myModal.hide()
    }
</script>

app/templates/index/svg-logo.html
<svg xlmns="http://www.w3.org/2000/svg" width="300" height="300" viewBOx="0 0 300 300"><rect fill="#ddd" width="300" height="300" /><text fill="rgba(0,0,0,0.5)" font-family="sans-serif" font-size="30" dy="10.5" font-weight="bold" x="50%" y="50%" text-anchor="middle">loading ...</text></svg>

app/templates/product/product.html
{% extends 'base.html' %}

{% block body %}

	{% include 'index/header.html' %}

	<div class="container">
        <div class="d-flex justify-content-center flex-wrap p-4">
			<img data-loader="#imageLoader" class="width-300 product-image card-img-top" width="100%" src="https://opri.sg/wp-content/uploads/2020/08/covid-square-image.png" hidden="true"/>
			<div id="imageLoader" class="skeleton-loader-image"></div>

			<div class="col-md-4 p-2">
	            <p class="card-text skeleton-loader">{{product.name}}</p>
	            <strike class="text-warning skeleton-loader">{{product.preprice}}</strike>
	            <p><strong class="skeleton-loader">{{product.price}}</strong></p>
	            <hr>
		        <form>
		        	<div>
		        		<p>Quantity</p>
						<input id="numberInput" class="number-input" type="number" name="number" min="1" max="10" data-target="#numberDisplay" hidden />
						<div class="input-group mb-3">
							<button class="btn btn-outline-secondary number-input-minus" data-number-input="#numberInput" type="button">-</button>
							<div id="numberDisplay" class="number-input-display border border-dark text-center p-2 w-25">1</div>
							<button class="btn btn-outline-secondary number-input-plus" data-number-input="#numberInput" type="button">+</button>
						</div>
					</div>
	            	<p><strong class="skeleton-loader">{{product.price}}</strong></p>
            		<button class="btn btn-primary hover-scale-2" type="submit">Order</button>
	            </form>
			</div>
		</div>
	</div>

	{% include 'index/product-search.html' %}
	{% include 'index/products.html' %}

{% endblock %}

app/templates/signin_signup/signin-signup.html
{% extends 'base.html' %}


{% block body %}

<style>
html,
body {
  height: 100%;
}

body {
    /*display: flex;*/
    /*align-items: center;*/
    padding-top: 3rem;
    padding-bottom: 3rem;
    /*background:  linear-gradient(to bottom, #ff572299, white);*/
    background-image: url("{{url_for('static', filename='img/poster1.png')}}");
    background-size: 100%;
    background-repeat: no-repeat;

}
</style>

<main class="form-signin text-center border bg-light rounded shadow">
    <img class="mb-4 rounded-circle" src="{{url_for('static', filename='img/logo-yellow.jpg')}}" alt="" width="70">

    <ul class="d-flex justify-content-center nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">LOGIN</button>
        </li>

        <li class="nav-item" role="presentation">
            <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">SIGN UP</button>
        </li>
    </ul>

    <div class="tab-content" id="pills-tabContent" style="transition: height 1s ease-out;">
        <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
            <form>
                <div class="form-floating my-2">
                    <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
                    <label for="floatingInput">Email address</label>
                </div>

                <div class="form-floating my-2">
                    <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
                    <label for="floatingPassword">Password</label>
                </div>
                <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
            </form>
        </div>
        <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
            <form>
                <div class="form-floating my-2">
                    <input type="text" class="form-control" id="floatingName" placeholder="Your Name">
                    <label for="floatingPassword">Your Name</label>
                </div>
                <div class="form-floating my-2">
                    <input type="email" class="form-control" id="floatingEmail" placeholder="Email">
                    <label for="floatingPassword">Email</label>
                </div>

                <div class="form-floating my-2">
                    <input type="number" class="form-control" id="floatingTelephone" placeholder="Telephone">
                    <label for="floatingPassword">Telephone</label>
                </div>

                <div class="form-floating my-2">
                    <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
                    <label for="floatingPassword">Password</label>
                </div>
                <div class="form-floating my-2">
                    <input type="password" class="form-control" id="floatingConfirmPassword" placeholder="Confirm Password">
                    <label for="floatingPassword">Confirm Password</label>
                </div>
                <button class="w-100 btn btn-lg btn-primary" type="submit">Sign up</button>
            </form>
        </div>
            <p class="mt-5 mb-3 text-muted">&copy; AMOBIT TECHNOLOGIES</p>
    </div>

</main>
{% endblock %}


{% block footer %}
{% endblock %}